### ISSUE TITLE
 Change color for Obsidian TODO | Text-based GTD plugin [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by andynameistaken** [crashmoney/obsidian-typewriter#25]
![image](https://user-images.githubusercontent.com/15692002/206953314-07d146fd-c318-4fd7-b21b-a4a34195356f.png)

Coulours on date label should have more contrast

**Comment by crashmoney** [comment]
Hi @andynameistaken, I just pushed an update that should fix this. Can you try updating the theme and letting me know whether the contrast works better now?

**Comment by andynameistaken** [comment]
It works better, but I think it is still not enough to be readable (especially with high ambient light). I would suggest to make background color darker (or letters black, but it could  make it look less modern, I am not sure )

**Comment by crashmoney** [comment]
Making the letters black made the overdue dates illegible in my testing, but I'll check out changing the background colors to something darker 👍🏻

**Comment by andynameistaken** [comment]
Thanks, except this small issue, it's a nice theme with really good typography :)

**Comment by crashmoney** [comment]
Would orange #e87d3e for overdue and yellow #e5b567 for due today against white date text work better?
